name: drupal
recipe: lamp
config:
  webroot: ./web
  php: 8.2
  database: mariadb
env_file:
  - defaults.env
services:
  database:
    type: mariadb
    creds:
      user: drupal
      password: drupal
    build_as_root:
      # Create databases for each drupal site using db_{lable} as a naming convention.
      - mysql -h database -P 3306 -u root -e "CREATE DATABASE IF NOT EXISTS db_youphrases; GRANT ALL PRIVILEGES ON db_youphrases.* TO 'drupal'@'%' IDENTIFIED by 'drupal';"
      - mysql -h database -P 3306 -u root -e "CREATE DATABASE IF NOT EXISTS db_eltera; GRANT ALL PRIVILEGES ON db_eltera.* TO 'drupal'@'%' IDENTIFIED by 'drupal';"
  appserver:
    xdebug: true
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/
proxy:
  mailhog:
    - mail.drupal.lndo.site
  appserver:
    - default.lndo.site
    - youphrases.lndo.site
    - eltera.lndo.site
