label: 'Bloco quem está ligado'
display:
  default:
    display_title: Predefinido
    display_options:
      title: 'Utilizadores ligados'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      empty:
        area_text_custom:
          content: 'Atualmente, existem 0 utilizadores ligados.'
      filters:
        access:
          expose:
            label: 'Último acesso'
            description: 'Um utilizador é considerado "ligado" por este intervalo de tempo, após ter visualizado uma página pela última vez.'
      header:
        result:
          content: 'Atualmente, existem @total utilizadores ligaos.'
  who_s_online_block:
    display_title: 'Utilizadores ligados'
    display_options:
      display_description: 'Uma lista de utilizadores que estão atualmente com sessão iniciada.'
      block_description: 'Utilizadores ligados'
