label: 'Novos utilizadores'
description: 'Mostra uma lista de contas de utilizador mais recentes no sítio.'
display:
  default:
    display_title: Predefinido
    display_options:
      title: 'Novos utilizadores'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
  block_1:
    display_title: 'Novos utilizadores'
    display_options:
      display_description: 'Uma lista de utilizadores novos'
      block_description: 'Novos utilizadores'
      block_category: Utilizador
