label: 'Conteúdo recente'
description: 'Conteúdo recente.'
display:
  default:
    display_title: Predefinido
    display_options:
      title: 'Conteúdo recente'
      fields:
        changed:
          separator: ', '
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      empty:
        area_text_custom:
          content: 'Conteúdo não disponível'
      use_more_text: Mais
  block_1:
    display_title: Bloco
