_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en-gb
uuid: 4ffa9e50-63ca-4535-91a9-78c4ed9c887a
name: 'website name'
mail: example.user@example.site
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en-gb
